name: eco
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  intl: ^0.19.0
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  rxdart: ^0.28.0
  lottie: ^3.1.2
  cached_network_image: ^3.4.0
  eva_icons_flutter: ^3.1.0
  firebase_core: ^3.5.0
  cloud_firestore: ^5.4.2
  go_router: ^14.2.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl_utils: 2.8.7
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lottie/

  fonts:
    - family: NotoKufiArabic
      fonts:
        - asset: assets/fonts/noto_kufi_arabic/NotoKufiArabic-Regular.ttf
          weight: 400
        - asset: assets/fonts/noto_kufi_arabic/NotoKufiArabic-Bold.ttf
          weight: 700
        - asset: assets/fonts/noto_kufi_arabic/NotoKufiArabic-Light.ttf
          weight: 300
        - asset: assets/fonts/noto_kufi_arabic/NotoKufiArabic-Medium.ttf
          weight: 500
        - asset: assets/fonts/noto_kufi_arabic/NotoKufiArabic-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/noto_kufi_arabic/NotoKufiArabic-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/noto_kufi_arabic/NotoKufiArabic-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/noto_kufi_arabic/NotoKufiArabic-Thin.ttf
          weight: 100
        - asset: assets/fonts/noto_kufi_arabic/NotoKufiArabic-Black.ttf
          weight: 900

    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Black.ttf
          weight: 900
        - asset: assets/fonts/montserrat/Montserrat-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/montserrat/Montserrat-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/montserrat/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/montserrat/Montserrat-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/montserrat/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/montserrat/Montserrat-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/montserrat/Montserrat-Italic.ttf
          style: italic
        - asset: assets/fonts/montserrat/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/montserrat/Montserrat-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/montserrat/Montserrat-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/montserrat/Montserrat-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/montserrat/Montserrat-Thin.ttf
          weight: 100
        - asset: assets/fonts/montserrat/Montserrat-ThinItalic.ttf
          weight: 100
          style: italic

flutter_intl:
  enabled: true # Required. Must be set to true to activate the plugin. Default: false
  class_name: GetTranslation # Changed from S to GetTranslation
  main_locale: en # Optional. Sets the main locale used for generating localization files. Provided value should consist of language code and optional script and country codes separated with underscore (e.g. 'en', 'en_GB', 'zh_Hans', 'zh_Hans_CN'). Default: en
  arb_dir: lib/utils/localization/l10n # Changed directory for ARB files
  output_dir: lib/utils/localization/generated # Changed directory for generated localization files
  use_deferred_loading: false # Optional. Must be set to true to generate localization code that is loaded with deferred loading. Default: false
